- hosts: raspberrypi
  become: yes
  tasks:
    - name: Ensure Python is installed
      raw: sudo apt install -y python3

    - name: Upload FastAPI app
      copy:
        src: ./app
        dest: /home/pi/myapp
        owner: pi
        group: pi
        mode: 0755

    - name: Install dependencies
      apt:
        name: python3-uvicorn
        state: present

    - name: Run FastAPI app
      shell: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
