name: Pylint Report

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-json2html

      - name: Run Pylint and generate HTML report
        run: |
          pylint --exit-zero $(git ls-files '*.py') --output-format=json > pylint-report.json
          pylint-json2html -f json -o pylint-report.html pylint-report.json

      - name: Upload Pylint report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: pylint-report.html
